
/**
  * Generated content
  */
export const Xp = {
  "accessibility-wizard": "../../assets/xp/Accessibility Wizard.png",
  "accessibility": "../../assets/xp/Accessibility.png",
  "activation": "../../assets/xp/Activation.png",
  "add-network-place": "../../assets/xp/Add Network Place.png",
  "add-new-hardware": "../../assets/xp/Add New Hardware.png",
  "add-new-programs": "../../assets/xp/Add New Programs.png",
  "add-or-remove-windows-components": "../../assets/xp/Add or Remove Windows Components.png",
  "add": "../../assets/xp/Add.png",
  "additional-settings": "../../assets/xp/Additional Settings.png",
  "address-book": "../../assets/xp/Address Book.png",
  "administrative-tools": "../../assets/xp/Administrative Tools.png",
  "alert": "../../assets/xp/Alert.png",
  "appearance": "../../assets/xp/Appearance.png",
  "application-window": "../../assets/xp/Application Window.png",
  "attributes": "../../assets/xp/Attributes.png",
  "audio-cd": "../../assets/xp/Audio CD.png",
  "audio-devices": "../../assets/xp/Audio Devices.png",
  "authorization-manager": "../../assets/xp/Authorization Manager.png",
  "auto-complete": "../../assets/xp/AutoComplete.png",
  "bat": "../../assets/xp/BAT.png",
  "blg": "../../assets/xp/BLG.png",
  "back": "../../assets/xp/Back.png",
  "backup-wizard": "../../assets/xp/Backup Wizard.png",
  "backups": "../../assets/xp/Backups.png",
  "battery-backup": "../../assets/xp/Battery Backup.png",
  "bitmap": "../../assets/xp/Bitmap.png",
  "bluetooth-access-point": "../../assets/xp/Bluetooth Access Point.png",
  "bluetooth-devices": "../../assets/xp/Bluetooth Devices.png",
  "bridged-connection": "../../assets/xp/Bridged Connection.png",
  "briefcase": "../../assets/xp/Briefcase.png",
  "burn-audio-cd": "../../assets/xp/Burn audio CD.png",
  "cab": "../../assets/xp/CAB.png",
  "css": "../../assets/xp/CSS.png",
  "calculator": "../../assets/xp/Calculator.png",
  "camcorder": "../../assets/xp/Camcorder.png",
  "change-connection-settings": "../../assets/xp/Change Connection Settings.png",
  "change-language": "../../assets/xp/Change Language.png",
  "change-or-remove-programs": "../../assets/xp/Change or Remove Programs.png",
  "charmap": "../../assets/xp/Charmap.png",
  "checklist": "../../assets/xp/Checklist.png",
  "chip": "../../assets/xp/Chip.png",
  "click-to-record": "../../assets/xp/Click To Record.png",
  "color-profile": "../../assets/xp/Color Profile.png",
  "color-scan": "../../assets/xp/Color Scan.png",
  "command-prompt": "../../assets/xp/Command Prompt.png",
  "compact-flash-card": "../../assets/xp/CompactFlash card.png",
  "component-services": "../../assets/xp/Component Services.png",
  "compose-a-fax": "../../assets/xp/Compose a fax.png",
  "computer-management": "../../assets/xp/Computer Management.png",
  "computer-to-computer-connection": "../../assets/xp/Computer to Computer connection.png",
  "configure-your-server-wizard": "../../assets/xp/Configure Your Server Wizard.png",
  "connection-manager": "../../assets/xp/Connection Manager.png",
  "connection-status": "../../assets/xp/Connection Status.png",
  "content-advisor": "../../assets/xp/Content Advisor.png",
  "control-panel": "../../assets/xp/Control Panel.png",
  "copy-to": "../../assets/xp/Copy To.png",
  "copy-to-disc": "../../assets/xp/Copy to disc.png",
  "copy": "../../assets/xp/Copy.png",
  "copying-conflict": "../../assets/xp/Copying Conflict.png",
  "cover-page-editor": "../../assets/xp/Cover Page Editor.png",
  "critical": "../../assets/xp/Critical.png",
  "cut": "../../assets/xp/Cut.png",
  "dll": "../../assets/xp/DLL.png",
  "dvd-alt": "../../assets/xp/DVD alt.png",
  "data-execution-prevention": "../../assets/xp/Data Execution Prevention.png",
  "date-and-region": "../../assets/xp/Date and Region.png",
  "date-and-time": "../../assets/xp/Date and Time.png",
  "default-programs-sp1-version": "../../assets/xp/Default Programs SP1 Version.png",
  "default-programs": "../../assets/xp/Default Programs.png",
  "default": "../../assets/xp/Default.png",
  "delete-confirmation": "../../assets/xp/Delete Confirmation.png",
  "delete-internet-history": "../../assets/xp/Delete Internet History.png",
  "delete": "../../assets/xp/Delete.png",
  "detail-view": "../../assets/xp/Detail View.png",
  "dial-up-connection": "../../assets/xp/Dial Up Connection.png",
  "digital-camera": "../../assets/xp/Digital Camera.png",
  "direct-connection": "../../assets/xp/Direct Connection.png",
  "direct-x": "../../assets/xp/DirectX.png",
  "disable-network-connection": "../../assets/xp/Disable Network Connection.png",
  "discard-fax": "../../assets/xp/Discard Fax.png",
  "disconnect-network-drive": "../../assets/xp/Disconnect Network Drive.png",
  "disk-cleanup": "../../assets/xp/Disk Cleanup.png",
  "disk-defragmenter": "../../assets/xp/Disk Defragmenter.png",
  "disk-management": "../../assets/xp/Disk Management.png",
  "display-adaptor": "../../assets/xp/Display Adaptor.png",
  "display-properties": "../../assets/xp/Display Properties.png",
  "document-search": "../../assets/xp/Document Search.png",
  "double-click": "../../assets/xp/Double Click.png",
  "entire-network": "../../assets/xp/Entire Network.png",
  "erase-disc": "../../assets/xp/Erase Disc.png",
  "erase": "../../assets/xp/Erase.png",
  "event-viewer": "../../assets/xp/Event Viewer.png",
  "exit": "../../assets/xp/Exit.png",
  "explorer-delete": "../../assets/xp/Explorer Delete.png",
  "favorites": "../../assets/xp/Favorites.png",
  "fax-archive": "../../assets/xp/Fax Archive.png",
  "fax-console": "../../assets/xp/Fax Console.png",
  "fax-cover-page": "../../assets/xp/Fax Cover Page.png",
  "fax-devices": "../../assets/xp/Fax Devices.png",
  "fax-event": "../../assets/xp/Fax Event.png",
  "fax-received-succesfully": "../../assets/xp/Fax Received Succesfully.png",
  "fax-sender-information": "../../assets/xp/Fax Sender Information.png",
  "fax-sent-succesfully": "../../assets/xp/Fax Sent Succesfully.png",
  "file-and-settings-transfer-wizard": "../../assets/xp/File and Settings Transfer Wizard.png",
  "floppy-disk": "../../assets/xp/Floppy Disk.png",
  "folder-closed": "../../assets/xp/Folder Closed.png",
  "folder-opened": "../../assets/xp/Folder Opened.png",
  "folder-options": "../../assets/xp/Folder Options.png",
  "folder-view-classic": "../../assets/xp/Folder View - Classic.png",
  "folder-view-common-tasks": "../../assets/xp/Folder View - Common Tasks.png",
  "folder-view": "../../assets/xp/Folder View.png",
  "folders-open-in-new-window": "../../assets/xp/Folders open in new window.png",
  "folders-open-in-same-window": "../../assets/xp/Folders open in same window.png",
  "font-similarity-view": "../../assets/xp/Font Similarity View.png",
  "font": "../../assets/xp/Font.png",
  "font2": "../../assets/xp/Font2.png",
  "fonts": "../../assets/xp/Fonts.png",
  "full-screen": "../../assets/xp/Full Screen.png",
  "gif": "../../assets/xp/GIF.png",
  "game-controller": "../../assets/xp/Game Controller.png",
  "generic-audio": "../../assets/xp/Generic Audio.png",
  "generic-document": "../../assets/xp/Generic Document.png",
  "generic-media": "../../assets/xp/Generic Media.png",
  "generic-text-document": "../../assets/xp/Generic Text Document.png",
  "generic-video": "../../assets/xp/Generic Video.png",
  "get-going-with-tablet-pc": "../../assets/xp/Get Going with Tablet PC.png",
  "get-pictures": "../../assets/xp/Get Pictures.png",
  "get-support": "../../assets/xp/Get Support.png",
  "go": "../../assets/xp/Go.png",
  "graph-view": "../../assets/xp/Graph View.png",
  "grayscale-scan": "../../assets/xp/Grayscale Scan.png",
  "hlp": "../../assets/xp/HLP.png",
  "html": "../../assets/xp/HTML.png",
  "hearts": "../../assets/xp/Hearts.png",
  "help-and-support-change-view1": "../../assets/xp/Help and Support - Change view 1.png",
  "help-and-support-change-view2": "../../assets/xp/Help and Support - Change view 2.png",
  "help-and-support-index": "../../assets/xp/Help and Support - Index.png",
  "help-and-support-task-list": "../../assets/xp/Help and Support - Task List.png",
  "help-and-support": "../../assets/xp/Help and Support.png",
  "hibernate": "../../assets/xp/Hibernate.png",
  "high-contrast-settings": "../../assets/xp/High Contrast Settings.png",
  "hyper-terminal": "../../assets/xp/Hyper Terminal.png",
  "ie-discuss": "../../assets/xp/IE Discuss.png",
  "ie-edit": "../../assets/xp/IE Edit.png",
  "ie-encoding": "../../assets/xp/IE Encoding.png",
  "ie-enlarge-image": "../../assets/xp/IE Enlarge Image.png",
  "ie-history": "../../assets/xp/IE History.png",
  "ie-home": "../../assets/xp/IE Home.png",
  "ie-media": "../../assets/xp/IE Media.png",
  "ie-refresh": "../../assets/xp/IE Refresh.png",
  "ie-shrink-image": "../../assets/xp/IE Shrink Image.png",
  "ie-size": "../../assets/xp/IE Size.png",
  "ie-stop": "../../assets/xp/IE Stop.png",
  "inf": "../../assets/xp/INF.png",
  "ir-file-transfer": "../../assets/xp/IR File Transfer.png",
  "icon-view": "../../assets/xp/Icon View.png",
  "iexpress": "../../assets/xp/Iexpress.png",
  "important": "../../assets/xp/Important.png",
  "incoming-connections": "../../assets/xp/Incoming Connections.png",
  "indexing-service": "../../assets/xp/Indexing Service.png",
  "information-bar": "../../assets/xp/Information Bar.png",
  "information": "../../assets/xp/Information.png",
  "ink-ball": "../../assets/xp/InkBall.png",
  "input-panel": "../../assets/xp/Input Panel.png",
  "internet-backgammon": "../../assets/xp/Internet Backgammon.png",
  "internet-checkers": "../../assets/xp/Internet Checkers.png",
  "internet-connection-wizard": "../../assets/xp/Internet Connection Wizard.png",
  "internet-explorer6": "../../assets/xp/Internet Explorer 6.png",
  "internet-hearts": "../../assets/xp/Internet Hearts.png",
  "internet-information-services6": "../../assets/xp/Internet Information Services 6.png",
  "internet-options": "../../assets/xp/Internet Options.png",
  "internet-reversi": "../../assets/xp/Internet Reversi.png",
  "internet-shortcut": "../../assets/xp/Internet Shortcut.png",
  "internet-spades": "../../assets/xp/Internet Spades.png",
  "jaz-drive": "../../assets/xp/JAZ Drive.png",
  "jpg": "../../assets/xp/JPG.png",
  "java-script": "../../assets/xp/Java Script.png",
  "journal-note": "../../assets/xp/Journal Note.png",
  "journal-template": "../../assets/xp/Journal Template.png",
  "legacy-floppy-disk": "../../assets/xp/Legacy Floppy Disk.png",
  "local-disk": "../../assets/xp/Local Disk.png",
  "local-security-policy": "../../assets/xp/Local Security Policy.png",
  "lock": "../../assets/xp/Lock.png",
  "login-question": "../../assets/xp/Login Question.png",
  "logout": "../../assets/xp/Logout.png",
  "mp3-player": "../../assets/xp/MP3 player.png",
  "msn-email": "../../assets/xp/MSN Email.png",
  "msn-messenger": "../../assets/xp/MSN Messenger.png",
  "mswmm": "../../assets/xp/MSWMM.png",
  "magnifier": "../../assets/xp/Magnifier.png",
  "malicious-software-removal-tool": "../../assets/xp/Malicious Software Removal Tool.png",
  "manage-server-licenses": "../../assets/xp/Manage Server Licenses.png",
  "manage-server-roles": "../../assets/xp/Manage Server Roles.png",
  "manage-your-server": "../../assets/xp/Manage Your Server.png",
  "map-network-drive": "../../assets/xp/Map Network Drive.png",
  "maximize": "../../assets/xp/Maximize.png",
  "media-center-extender-manager": "../../assets/xp/Media Center Extender Manager.png",
  "media-center-file": "../../assets/xp/Media Center File.png",
  "media-center": "../../assets/xp/Media Center.png",
  "memory-stick-with-magic-gate": "../../assets/xp/Memory Stick with MagicGate.png",
  "memory-stick": "../../assets/xp/Memory Stick.png",
  "microsoft-active-sync": "../../assets/xp/Microsoft ActiveSync.png",
  "microsoft-update": "../../assets/xp/Microsoft Update.png",
  "microsoft-windows-network": "../../assets/xp/Microsoft Windows Network.png",
  "minimize": "../../assets/xp/Minimize.png",
  "missing-setup-information": "../../assets/xp/Missing Setup Information.png",
  "mobile-device": "../../assets/xp/Mobile Device.png",
  "modem": "../../assets/xp/Modem.png",
  "move-to": "../../assets/xp/Move To.png",
  "move-this-folder": "../../assets/xp/Move this folder.png",
  "move-to-folder": "../../assets/xp/Move to folder.png",
  "mute": "../../assets/xp/Mute.png",
  "my-computer": "../../assets/xp/My Computer.png",
  "my-documents": "../../assets/xp/My Documents.png",
  "my-music": "../../assets/xp/My Music.png",
  "my-network-places": "../../assets/xp/My Network Places.png",
  "my-pictures": "../../assets/xp/My Pictures.png",
  "my-videos": "../../assets/xp/My Videos.png",
  "netmeeting": "../../assets/xp/Netmeeting.png",
  "network-connection": "../../assets/xp/Network Connection.png",
  "network-connections": "../../assets/xp/Network Connections.png",
  "network-drive-disconnected": "../../assets/xp/Network Drive Disconnected.png",
  "network-drive": "../../assets/xp/Network Drive.png",
  "network-fax": "../../assets/xp/Network Fax.png",
  "network-folder": "../../assets/xp/Network Folder.png",
  "network-setup": "../../assets/xp/Network Setup.png",
  "network-and-internet": "../../assets/xp/Network and Internet.png",
  "network-printer": "../../assets/xp/Network printer.png",
  "new-folder": "../../assets/xp/New Folder.png",
  "new-imaging-device": "../../assets/xp/New Imaging Device.png",
  "new-internet-connection": "../../assets/xp/New Internet Connection.png",
  "new-network-connection": "../../assets/xp/New Network Connection.png",
  "new-printer": "../../assets/xp/New Printer.png",
  "new-scheduled-task": "../../assets/xp/New Scheduled Task.png",
  "odbc-data-sources": "../../assets/xp/ODBC Data Sources.png",
  "oe-attatch": "../../assets/xp/OE Attatch.png",
  "oe-create-mail": "../../assets/xp/OE Create Mail.png",
  "oe-decode": "../../assets/xp/OE Decode.png",
  "oe-encrypt": "../../assets/xp/OE Encrypt.png",
  "oe-folder-list": "../../assets/xp/OE Folder List.png",
  "oe-forward": "../../assets/xp/OE Forward.png",
  "oe-inbox": "../../assets/xp/OE Inbox.png",
  "oe-mark-as-read": "../../assets/xp/OE Mark as read.png",
  "oe-mark-as-unread": "../../assets/xp/OE Mark as unread.png",
  "oe-news-post": "../../assets/xp/OE News Post.png",
  "oe-outbox": "../../assets/xp/OE Outbox.png",
  "oe-preview-pane": "../../assets/xp/OE Preview Pane.png",
  "oe-recipients": "../../assets/xp/OE Recipients.png",
  "oe-reply-all": "../../assets/xp/OE Reply All.png",
  "oe-reply": "../../assets/xp/OE Reply.png",
  "oe-send-and-receive": "../../assets/xp/OE Send and Receive.png",
  "oe-send": "../../assets/xp/OE Send.png",
  "oe-sent-items": "../../assets/xp/OE Sent Items.png",
  "oe-sign": "../../assets/xp/OE Sign.png",
  "oe-signature": "../../assets/xp/OE Signature.png",
  "oe-unscramble": "../../assets/xp/OE Unscramble.png",
  "offline-web-pages": "../../assets/xp/Offline Web Pages.png",
  "on-screen-keyboard": "../../assets/xp/On-Screen Keyboard.png",
  "open": "../../assets/xp/Open.png",
  "open-type": "../../assets/xp/OpenType.png",
  "optical-drive": "../../assets/xp/Optical Drive.png",
  "outlook-express": "../../assets/xp/Outlook Express.png",
  "pcmcia-card": "../../assets/xp/PCMCIA Card.png",
  "packager": "../../assets/xp/Packager.png",
  "padlock-alt": "../../assets/xp/Padlock Alt.png",
  "padlock": "../../assets/xp/Padlock.png",
  "paste": "../../assets/xp/Paste.png",
  "performance-monitor": "../../assets/xp/Performance Monitor.png",
  "performance": "../../assets/xp/Performance.png",
  "phone-and-modem-options": "../../assets/xp/Phone and Modem Options.png",
  "phone": "../../assets/xp/Phone.png",
  "play": "../../assets/xp/Play.png",
  "pop-up-allowed": "../../assets/xp/Pop up allowed.png",
  "pop-up-blocked": "../../assets/xp/Pop up blocked.png",
  "pop-up-information": "../../assets/xp/Pop up information.png",
  "portable-media-devices": "../../assets/xp/Portable Media Devices.png",
  "power-options": "../../assets/xp/Power Options.png",
  "power-status": "../../assets/xp/Power Status.png",
  "power": "../../assets/xp/Power.png",
  "print-server-properties": "../../assets/xp/Print Server Properties.png",
  "print-photos": "../../assets/xp/Print photos.png",
  "print-to-file": "../../assets/xp/Print to file.png",
  "printer-missing": "../../assets/xp/Printer Missing.png",
  "printers-and-faxes": "../../assets/xp/Printers and Faxes.png",
  "printers-and-hardware": "../../assets/xp/Printers and Hardware.png",
  "privacy": "../../assets/xp/Privacy.png",
  "programs": "../../assets/xp/Programs.png",
  "prohibited": "../../assets/xp/Prohibited.png",
  "properties": "../../assets/xp/Properties.png",
  "proxy-server": "../../assets/xp/Proxy Server.png",
  "publish-photos-to-web": "../../assets/xp/Publish photos to web.png",
  "publish-to-web": "../../assets/xp/Publish to web.png",
  "question": "../../assets/xp/Question.png",
  "rtc-share": "../../assets/xp/RTC Share.png",
  "rtf": "../../assets/xp/RTF.png",
  "recent-documents": "../../assets/xp/Recent Documents.png",
  "record": "../../assets/xp/Record.png",
  "recycle-bin-empty": "../../assets/xp/Recycle Bin empty.png",
  "recycle-bin-full": "../../assets/xp/Recycle Bin full.png",
  "redo": "../../assets/xp/Redo.png",
  "regional-settings": "../../assets/xp/Regional Settings.png",
  "registry-document": "../../assets/xp/Registry Document.png",
  "registry-editor": "../../assets/xp/Registry Editor.png",
  "related-web-content": "../../assets/xp/Related Web Content.png",
  "remote-access-service": "../../assets/xp/Remote Access Service.png",
  "remote-assistance": "../../assets/xp/Remote Assistance.png",
  "remote-desktop-server": "../../assets/xp/Remote Desktop Server.png",
  "remote-desktop": "../../assets/xp/Remote Desktop.png",
  "removable-media": "../../assets/xp/Removable Media.png",
  "rename": "../../assets/xp/Rename.png",
  "restart": "../../assets/xp/Restart.png",
  "restore-all-items": "../../assets/xp/Restore All Items.png",
  "restore": "../../assets/xp/Restore.png",
  "restricted": "../../assets/xp/Restricted.png",
  "router": "../../assets/xp/Router.png",
  "run": "../../assets/xp/Run.png",
  "sd-card-alt": "../../assets/xp/SD Card - Alt.png",
  "sd-card": "../../assets/xp/SD Card.png",
  "safely-remove-hardware": "../../assets/xp/Safely Remove Hardware.png",
  "save": "../../assets/xp/Save.png",
  "scanner-and-camera-wizard": "../../assets/xp/Scanner and Camera Wizard.png",
  "scanners-and-cameras": "../../assets/xp/Scanners and Cameras.png",
  "scheduled-tasks": "../../assets/xp/Scheduled Tasks.png",
  "scrap": "../../assets/xp/Scrap.png",
  "script-component": "../../assets/xp/Script Component.png",
  "search-results": "../../assets/xp/Search Results.png",
  "search-for-people": "../../assets/xp/Search for people.png",
  "security-ok": "../../assets/xp/Security - Ok.png",
  "security-alert": "../../assets/xp/Security Alert.png",
  "security-center": "../../assets/xp/Security Center.png",
  "security-error": "../../assets/xp/Security Error.png",
  "security-question": "../../assets/xp/Security Question.png",
  "security-settings": "../../assets/xp/Security Settings.png",
  "send-a-fax": "../../assets/xp/Send a Fax.png",
  "serial-connection": "../../assets/xp/Serial Connection.png",
  "server-license": "../../assets/xp/Server License.png",
  "services": "../../assets/xp/Services.png",
  "settings-alert": "../../assets/xp/Settings Alert.png",
  "setup-language": "../../assets/xp/Setup Language.png",
  "setup-skip": "../../assets/xp/Setup Skip.png",
  "setup-back": "../../assets/xp/Setup back.png",
  "setup-task": "../../assets/xp/Setup task.png",
  "setup": "../../assets/xp/Setup.png",
  "shared-folder-alt": "../../assets/xp/Shared Folder Alt.png",
  "shared-folder": "../../assets/xp/Shared Folder.png",
  "shared-printer": "../../assets/xp/Shared Printer.png",
  "sharing-hand": "../../assets/xp/Sharing Hand.png",
  "shortcut-overlay": "../../assets/xp/Shortcut overlay.png",
  "single-click": "../../assets/xp/Single Click.png",
  "slideshow": "../../assets/xp/Slideshow.png",
  "smart-card-reader": "../../assets/xp/Smart Card Reader.png",
  "smart-media-card": "../../assets/xp/SmartMedia Card.png",
  "smart-screen": "../../assets/xp/SmartScreen.png",
  "sort-alphabetically": "../../assets/xp/Sort Alphabetically.png",
  "sort-by-date": "../../assets/xp/Sort by date.png",
  "sort-by-size": "../../assets/xp/Sort by size.png",
  "speech": "../../assets/xp/Speech.png",
  "spider-solitaire": "../../assets/xp/Spider Solitaire.png",
  "standby": "../../assets/xp/Standby.png",
  "start-menu-programs-alt": "../../assets/xp/Start Menu Programs Alt.png",
  "start-menu-programs": "../../assets/xp/Start Menu Programs.png",
  "sticky-notes": "../../assets/xp/StickyNotes.png",
  "stop": "../../assets/xp/Stop.png",
  "success": "../../assets/xp/Success.png",
  "support-topic": "../../assets/xp/Support Topic.png",
  "switch-user": "../../assets/xp/Switch User.png",
  "sync-all": "../../assets/xp/Sync All.png",
  "sync": "../../assets/xp/Sync.png",
  "synchronize": "../../assets/xp/Synchronize.png",
  "system-information": "../../assets/xp/System Information.png",
  "system-properties": "../../assets/xp/System Properties.png",
  "system-restore": "../../assets/xp/System Restore.png",
  "tiff": "../../assets/xp/TIFF.png",
  "txt": "../../assets/xp/TXT.png",
  "tablet-and-pen-settings": "../../assets/xp/Tablet and Pen settings.png",
  "take-picture": "../../assets/xp/Take Picture.png",
  "tape-drive2": "../../assets/xp/Tape Drive 2.png",
  "tape-drive": "../../assets/xp/Tape Drive.png",
  "task-manager": "../../assets/xp/Task Manager.png",
  "taskbar-and-start-menu": "../../assets/xp/Taskbar and Start Menu.png",
  "theme": "../../assets/xp/Theme.png",
  "thumbnail-view": "../../assets/xp/Thumbnail View.png",
  "tile-view": "../../assets/xp/Tile View.png",
  "tip-of-the-day": "../../assets/xp/Tip of the day.png",
  "tour-xp": "../../assets/xp/Tour XP.png",
  "troubleshoot": "../../assets/xp/Troubleshoot.png",
  "true-type": "../../assets/xp/TrueType.png",
  "true-type2": "../../assets/xp/TrueType2.png",
  "tweak-ui": "../../assets/xp/Tweak UI.png",
  "uddi-services": "../../assets/xp/UDDI Services.png",
  "url": "../../assets/xp/URL.png",
  "undo": "../../assets/xp/Undo.png",
  "undock-pc": "../../assets/xp/Undock PC.png",
  "unknown-disc": "../../assets/xp/Unknown Disc.png",
  "up": "../../assets/xp/Up.png",
  "user-accounts": "../../assets/xp/User Accounts.png",
  "vbs": "../../assets/xp/VBS.png",
  "vpn-connection": "../../assets/xp/VPN Connection.png",
  "virus-protection": "../../assets/xp/Virus Protection.png",
  "volume-alt": "../../assets/xp/Volume Alt.png",
  "volume-level": "../../assets/xp/Volume Level.png",
  "wme-broadcast-company-meeting": "../../assets/xp/WME Broadcast Company Meeting.png",
  "wme-broadcast-live-event": "../../assets/xp/WME Broadcast Live Event.png",
  "wme-capture-audio-or-video": "../../assets/xp/WME Capture Audio or Video.png",
  "wme-capture-screen": "../../assets/xp/WME Capture Screen.png",
  "wme-capture-live-content-for-streaming": "../../assets/xp/WME Capture live content for streaming.png",
  "wme-capture-live-content-locally": "../../assets/xp/WME Capture live content locally.png",
  "wme-convert-film": "../../assets/xp/WME Convert Film.png",
  "wme-convert-a-file": "../../assets/xp/WME Convert a File.png",
  "wme-custom-session": "../../assets/xp/WME Custom Session.png",
  "wmp-auto-playlist": "../../assets/xp/WMP Auto Playlist.png",
  "wmp-copy-protected-music": "../../assets/xp/WMP Copy Protected Music.png",
  "wmp-device-error": "../../assets/xp/WMP Device Error.png",
  "wmp-general-error": "../../assets/xp/WMP General Error.png",
  "wmp-import-audio-cd": "../../assets/xp/WMP Import Audio CD.png",
  "wmp-import-playlist": "../../assets/xp/WMP Import Playlist.png",
  "wmp-import-video": "../../assets/xp/WMP Import Video.png",
  "wmp-library-error": "../../assets/xp/WMP Library Error.png",
  "wmp-library": "../../assets/xp/WMP Library.png",
  "wmp-missing-disc": "../../assets/xp/WMP Missing Disc.png",
  "wmp-missing-file": "../../assets/xp/WMP Missing File.png",
  "wmp-network-error": "../../assets/xp/WMP Network Error.png",
  "wmp-performance": "../../assets/xp/WMP Performance.png",
  "wmp-playlist": "../../assets/xp/WMP Playlist.png",
  "wmp-plugin": "../../assets/xp/WMP Plugin.png",
  "wmp-stream-error": "../../assets/xp/WMP Stream Error.png",
  "wmp-timed-lyrics": "../../assets/xp/WMP Timed Lyrics.png",
  "wms-allow-connections": "../../assets/xp/WMS Allow Connections.png",
  "wms-broadcast-alt": "../../assets/xp/WMS Broadcast Alt.png",
  "wms-broadcast": "../../assets/xp/WMS Broadcast.png",
  "wms-cache": "../../assets/xp/WMS Cache.png",
  "wms-deny-connections": "../../assets/xp/WMS Deny Connections.png",
  "wms-playlist": "../../assets/xp/WMS Playlist.png",
  "wms-streaming-server": "../../assets/xp/WMS Streaming Server.png",
  "wms-troubleshoot": "../../assets/xp/WMS Troubleshoot.png",
  "wms-wrapper-file": "../../assets/xp/WMS Wrapper File.png",
  "wmv2": "../../assets/xp/WMV 2.png",
  "wmv": "../../assets/xp/WMV.png",
  "wri": "../../assets/xp/WRI.png",
  "web-services-printer": "../../assets/xp/Web services printer.png",
  "webcam": "../../assets/xp/Webcam.png",
  "windows-catalog": "../../assets/xp/Windows Catalog.png",
  "windows-journal-viewer": "../../assets/xp/Windows Journal Viewer.png",
  "windows-journal": "../../assets/xp/Windows Journal.png",
  "windows-media-connect": "../../assets/xp/Windows Media Connect.png",
  "windows-media-encoder": "../../assets/xp/Windows Media Encoder.png",
  "windows-media-player10": "../../assets/xp/Windows Media Player 10.png",
  "windows-media-player9": "../../assets/xp/Windows Media Player 9.png",
  "windows-media-player-skin": "../../assets/xp/Windows Media Player Skin.png",
  "windows-media-services": "../../assets/xp/Windows Media Services.png",
  "windows-messenger": "../../assets/xp/Windows Messenger.png",
  "windows-movie-maker": "../../assets/xp/Windows Movie Maker.png",
  "windows-picture-and-fax-viewer": "../../assets/xp/Windows Picture and Fax Viewer.png",
  "windows-update": "../../assets/xp/Windows Update.png",
  "wireless-connection-settings": "../../assets/xp/Wireless Connection Settings.png",
  "wireless-network-connection": "../../assets/xp/Wireless Network Connection.png",
  "wireless-network-setup": "../../assets/xp/Wireless Network Setup.png",
  "wizard": "../../assets/xp/Wizard.png",
  "wordpad": "../../assets/xp/Wordpad.png",
  "workgroup": "../../assets/xp/Workgroup.png",
  "write-files-to-disc": "../../assets/xp/Write Files to Disc.png",
  "xml": "../../assets/xp/XML.png",
  "xps-viewer": "../../assets/xp/XPS Viewer.png",
  "xps-document": "../../assets/xp/XPS document.png",
  "xpsp3-res-unknown1": "../../assets/xp/XPSP3RES Unknown 1.png",
  "xpsp3-res-unknown2": "../../assets/xp/XPSP3RES Unknown 2.png",
  "xsl": "../../assets/xp/XSL.png",
  "zip-drive": "../../assets/xp/ZIP Drive.png",
  "zip-folder": "../../assets/xp/Zip folder.png",
  "cd-r": "../../assets/xp/cd-r.png",
  "cd-rom": "../../assets/xp/cd-rom.png",
  "cd-rw": "../../assets/xp/cd-rw.png",
  "certificate": "../../assets/xp/certificate.png",
  "desktop": "../../assets/xp/desktop.png",
  "dialer": "../../assets/xp/dialer.png",
  "dvd-r": "../../assets/xp/dvd-r.png",
  "dvd-ram": "../../assets/xp/dvd-ram.png",
  "dvd-rom": "../../assets/xp/dvd-rom.png",
  "dvd-rw": "../../assets/xp/dvd-rw.png",
  "dvd": "../../assets/xp/dvd.png",
  "email": "../../assets/xp/email.png",
  "explorer-properties": "../../assets/xp/explorer properties.png",
  "explorer": "../../assets/xp/explorer.png",
  "fax": "../../assets/xp/fax.png",
  "firewall": "../../assets/xp/firewall.png",
  "forward": "../../assets/xp/forward.png",
  "freecell": "../../assets/xp/freecell.png",
  "key": "../../assets/xp/key.png",
  "keyboard": "../../assets/xp/keyboard.png",
  "minesweeper": "../../assets/xp/minesweeper.png",
  "mouse": "../../assets/xp/mouse.png",
  "msn": "../../assets/xp/msn.png",
  "narrator": "../../assets/xp/narrator.png",
  "notepad": "../../assets/xp/notepad.png",
  "paint": "../../assets/xp/paint.png",
  "pinball": "../../assets/xp/pinball.png",
  "printer": "../../assets/xp/printer.png",
  "scanner": "../../assets/xp/scanner.png",
  "search": "../../assets/xp/search.png",
  "solitaire": "../../assets/xp/solitaire.png",
  "volume": "../../assets/xp/volume.png"
}

export const XpSP2 = {
  "antenna-signal": "../../assets/xpsp2/Antenna Signal.png",
  "antenna": "../../assets/xpsp2/Antenna.png",
  "internet-connection-firewall-locked-down": "../../assets/xpsp2/Internet Connection Firewall - Locked Down.png",
  "internet-connection-firewall-off": "../../assets/xpsp2/Internet Connection Firewall - Off.png",
  "internet-connection-firewall": "../../assets/xpsp2/Internet Connection Firewall.png",
  "search-for-wireless-network": "../../assets/xpsp2/Search for Wireless Network.png",
  "security-options": "../../assets/xpsp2/Security Options.png",
  "wireless-network-connection": "../../assets/xpsp2/Wireless Network Connection.png"
}

export const Longhorn = {
  "active-contact": "../../assets/longhorn/Active Contact.png",
  "business-contact": "../../assets/longhorn/Business Contact.png",
  "contact-offline": "../../assets/longhorn/Contact Offline.png",
  "directory-services": "../../assets/longhorn/Directory Services.png",
  "my-games": "../../assets/longhorn/My Games.png",
  "new-contact": "../../assets/longhorn/New Contact.png",
  "parental-controls": "../../assets/longhorn/Parental Controls.png",
  "pending-contact": "../../assets/longhorn/Pending Contact.png",
  "presentation-host2": "../../assets/longhorn/Presentation Host 2.png",
  "presentation-host3": "../../assets/longhorn/Presentation Host 3.png",
  "presentation-host4": "../../assets/longhorn/Presentation Host 4.png",
  "presentation-host5": "../../assets/longhorn/Presentation Host 5.png",
  "presentation-host": "../../assets/longhorn/Presentation Host.png",
  "presentation-platform": "../../assets/longhorn/Presentation Platform.png",
  "usb": "../../assets/longhorn/USB.png"
}

export const Whistler = {
  "accessibility": "../../assets/whistler/Accessibility.png",
  "appearance-and-themes": "../../assets/whistler/Appearance and Themes.png",
  "back": "../../assets/whistler/Back.png",
  "explorer-delete": "../../assets/whistler/Explorer Delete.png",
  "favorites": "../../assets/whistler/Favorites.png",
  "forward": "../../assets/whistler/Forward.png",
  "help-and-support": "../../assets/whistler/Help and Support.png",
  "ie-favorites": "../../assets/whistler/IE Favorites.png",
  "ie-history": "../../assets/whistler/IE History.png",
  "ie-home": "../../assets/whistler/IE Home.png",
  "ie-personal-bar": "../../assets/whistler/IE Personal Bar.png",
  "ie-refresh": "../../assets/whistler/IE Refresh.png",
  "ie-search": "../../assets/whistler/IE Search.png",
  "ie-stop": "../../assets/whistler/IE Stop.png",
  "internet-options": "../../assets/whistler/Internet Options.png",
  "orb-drive": "../../assets/whistler/ORB Drive.png",
  "performance": "../../assets/whistler/Performance.png",
  "programs": "../../assets/whistler/Programs.png",
  "recycle-bin-empty": "../../assets/whistler/Recycle Bin empty.png",
  "recycle-bin-full": "../../assets/whistler/Recycle Bin full.png",
  "redo": "../../assets/whistler/Redo.png",
  "rename": "../../assets/whistler/Rename.png",
  "run": "../../assets/whistler/Run.png",
  "sd-card": "../../assets/whistler/SD Card.png",
  "switch-user": "../../assets/whistler/Switch User.png",
  "system-properties": "../../assets/whistler/System Properties.png",
  "undo": "../../assets/whistler/Undo.png",
  "up": "../../assets/whistler/Up.png",
  "update": "../../assets/whistler/Update.png",
  "user-accounts": "../../assets/whistler/User Accounts.png",
  "volume": "../../assets/whistler/Volume.png",
  "windows-media-player7": "../../assets/whistler/Windows Media Player 7.png"
}

export const Applications = {
  "acrobat-installer": "../../assets/applications/acrobat-installer.png",
  "klite-codec": "../../assets/applications/klite-codec.png",
  "pdf-file": "../../assets/applications/pdf-file.png",
  "vlc": "../../assets/applications/vlc.png",
  "winrar3": "../../assets/applications/winrar-3.png",
  "winrar6": "../../assets/applications/winrar-6.png"
}

export type IconPack = 'xp' | 'xpsp2' | 'longhorn' | 'whistler' | 'applications'

export const isTypeIconPack = (value: string) => ['xp', 'xpsp2', 'longhorn', 'whistler', 'applications'].indexOf(value) >= 0

export type IconPackXp = 'accessibility-wizard' | 'accessibility' | 'activation' | 'add-network-place' | 'add-new-hardware' | 'add-new-programs' | 'add-or-remove-windows-components' | 'add' | 'additional-settings' | 'address-book' | 'administrative-tools' | 'alert' | 'appearance' | 'application-window' | 'attributes' | 'audio-cd' | 'audio-devices' | 'authorization-manager' | 'auto-complete' | 'bat' | 'blg' | 'back' | 'backup-wizard' | 'backups' | 'battery-backup' | 'bitmap' | 'bluetooth-access-point' | 'bluetooth-devices' | 'bridged-connection' | 'briefcase' | 'burn-audio-cd' | 'cab' | 'css' | 'calculator' | 'camcorder' | 'change-connection-settings' | 'change-language' | 'change-or-remove-programs' | 'charmap' | 'checklist' | 'chip' | 'click-to-record' | 'color-profile' | 'color-scan' | 'command-prompt' | 'compact-flash-card' | 'component-services' | 'compose-a-fax' | 'computer-management' | 'computer-to-computer-connection' | 'configure-your-server-wizard' | 'connection-manager' | 'connection-status' | 'content-advisor' | 'control-panel' | 'copy-to' | 'copy-to-disc' | 'copy' | 'copying-conflict' | 'cover-page-editor' | 'critical' | 'cut' | 'dll' | 'dvd-alt' | 'data-execution-prevention' | 'date-and-region' | 'date-and-time' | 'default-programs-sp1-version' | 'default-programs' | 'default' | 'delete-confirmation' | 'delete-internet-history' | 'delete' | 'detail-view' | 'dial-up-connection' | 'digital-camera' | 'direct-connection' | 'direct-x' | 'disable-network-connection' | 'discard-fax' | 'disconnect-network-drive' | 'disk-cleanup' | 'disk-defragmenter' | 'disk-management' | 'display-adaptor' | 'display-properties' | 'document-search' | 'double-click' | 'entire-network' | 'erase-disc' | 'erase' | 'event-viewer' | 'exit' | 'explorer-delete' | 'favorites' | 'fax-archive' | 'fax-console' | 'fax-cover-page' | 'fax-devices' | 'fax-event' | 'fax-received-succesfully' | 'fax-sender-information' | 'fax-sent-succesfully' | 'file-and-settings-transfer-wizard' | 'floppy-disk' | 'folder-closed' | 'folder-opened' | 'folder-options' | 'folder-view-classic' | 'folder-view-common-tasks' | 'folder-view' | 'folders-open-in-new-window' | 'folders-open-in-same-window' | 'font-similarity-view' | 'font' | 'font2' | 'fonts' | 'full-screen' | 'gif' | 'game-controller' | 'generic-audio' | 'generic-document' | 'generic-media' | 'generic-text-document' | 'generic-video' | 'get-going-with-tablet-pc' | 'get-pictures' | 'get-support' | 'go' | 'graph-view' | 'grayscale-scan' | 'hlp' | 'html' | 'hearts' | 'help-and-support-change-view1' | 'help-and-support-change-view2' | 'help-and-support-index' | 'help-and-support-task-list' | 'help-and-support' | 'hibernate' | 'high-contrast-settings' | 'hyper-terminal' | 'ie-discuss' | 'ie-edit' | 'ie-encoding' | 'ie-enlarge-image' | 'ie-history' | 'ie-home' | 'ie-media' | 'ie-refresh' | 'ie-shrink-image' | 'ie-size' | 'ie-stop' | 'inf' | 'ir-file-transfer' | 'icon-view' | 'iexpress' | 'important' | 'incoming-connections' | 'indexing-service' | 'information-bar' | 'information' | 'ink-ball' | 'input-panel' | 'internet-backgammon' | 'internet-checkers' | 'internet-connection-wizard' | 'internet-explorer6' | 'internet-hearts' | 'internet-information-services6' | 'internet-options' | 'internet-reversi' | 'internet-shortcut' | 'internet-spades' | 'jaz-drive' | 'jpg' | 'java-script' | 'journal-note' | 'journal-template' | 'legacy-floppy-disk' | 'local-disk' | 'local-security-policy' | 'lock' | 'login-question' | 'logout' | 'mp3-player' | 'msn-email' | 'msn-messenger' | 'mswmm' | 'magnifier' | 'malicious-software-removal-tool' | 'manage-server-licenses' | 'manage-server-roles' | 'manage-your-server' | 'map-network-drive' | 'maximize' | 'media-center-extender-manager' | 'media-center-file' | 'media-center' | 'memory-stick-with-magic-gate' | 'memory-stick' | 'microsoft-active-sync' | 'microsoft-update' | 'microsoft-windows-network' | 'minimize' | 'missing-setup-information' | 'mobile-device' | 'modem' | 'move-to' | 'move-this-folder' | 'move-to-folder' | 'mute' | 'my-computer' | 'my-documents' | 'my-music' | 'my-network-places' | 'my-pictures' | 'my-videos' | 'netmeeting' | 'network-connection' | 'network-connections' | 'network-drive-disconnected' | 'network-drive' | 'network-fax' | 'network-folder' | 'network-setup' | 'network-and-internet' | 'network-printer' | 'new-folder' | 'new-imaging-device' | 'new-internet-connection' | 'new-network-connection' | 'new-printer' | 'new-scheduled-task' | 'odbc-data-sources' | 'oe-attatch' | 'oe-create-mail' | 'oe-decode' | 'oe-encrypt' | 'oe-folder-list' | 'oe-forward' | 'oe-inbox' | 'oe-mark-as-read' | 'oe-mark-as-unread' | 'oe-news-post' | 'oe-outbox' | 'oe-preview-pane' | 'oe-recipients' | 'oe-reply-all' | 'oe-reply' | 'oe-send-and-receive' | 'oe-send' | 'oe-sent-items' | 'oe-sign' | 'oe-signature' | 'oe-unscramble' | 'offline-web-pages' | 'on-screen-keyboard' | 'open' | 'open-type' | 'optical-drive' | 'outlook-express' | 'pcmcia-card' | 'packager' | 'padlock-alt' | 'padlock' | 'paste' | 'performance-monitor' | 'performance' | 'phone-and-modem-options' | 'phone' | 'play' | 'pop-up-allowed' | 'pop-up-blocked' | 'pop-up-information' | 'portable-media-devices' | 'power-options' | 'power-status' | 'power' | 'print-server-properties' | 'print-photos' | 'print-to-file' | 'printer-missing' | 'printers-and-faxes' | 'printers-and-hardware' | 'privacy' | 'programs' | 'prohibited' | 'properties' | 'proxy-server' | 'publish-photos-to-web' | 'publish-to-web' | 'question' | 'rtc-share' | 'rtf' | 'recent-documents' | 'record' | 'recycle-bin-empty' | 'recycle-bin-full' | 'redo' | 'regional-settings' | 'registry-document' | 'registry-editor' | 'related-web-content' | 'remote-access-service' | 'remote-assistance' | 'remote-desktop-server' | 'remote-desktop' | 'removable-media' | 'rename' | 'restart' | 'restore-all-items' | 'restore' | 'restricted' | 'router' | 'run' | 'sd-card-alt' | 'sd-card' | 'safely-remove-hardware' | 'save' | 'scanner-and-camera-wizard' | 'scanners-and-cameras' | 'scheduled-tasks' | 'scrap' | 'script-component' | 'search-results' | 'search-for-people' | 'security-ok' | 'security-alert' | 'security-center' | 'security-error' | 'security-question' | 'security-settings' | 'send-a-fax' | 'serial-connection' | 'server-license' | 'services' | 'settings-alert' | 'setup-language' | 'setup-skip' | 'setup-back' | 'setup-task' | 'setup' | 'shared-folder-alt' | 'shared-folder' | 'shared-printer' | 'sharing-hand' | 'shortcut-overlay' | 'single-click' | 'slideshow' | 'smart-card-reader' | 'smart-media-card' | 'smart-screen' | 'sort-alphabetically' | 'sort-by-date' | 'sort-by-size' | 'speech' | 'spider-solitaire' | 'standby' | 'start-menu-programs-alt' | 'start-menu-programs' | 'sticky-notes' | 'stop' | 'success' | 'support-topic' | 'switch-user' | 'sync-all' | 'sync' | 'synchronize' | 'system-information' | 'system-properties' | 'system-restore' | 'tiff' | 'txt' | 'tablet-and-pen-settings' | 'take-picture' | 'tape-drive2' | 'tape-drive' | 'task-manager' | 'taskbar-and-start-menu' | 'theme' | 'thumbnail-view' | 'tile-view' | 'tip-of-the-day' | 'tour-xp' | 'troubleshoot' | 'true-type' | 'true-type2' | 'tweak-ui' | 'uddi-services' | 'url' | 'undo' | 'undock-pc' | 'unknown-disc' | 'up' | 'user-accounts' | 'vbs' | 'vpn-connection' | 'virus-protection' | 'volume-alt' | 'volume-level' | 'wme-broadcast-company-meeting' | 'wme-broadcast-live-event' | 'wme-capture-audio-or-video' | 'wme-capture-screen' | 'wme-capture-live-content-for-streaming' | 'wme-capture-live-content-locally' | 'wme-convert-film' | 'wme-convert-a-file' | 'wme-custom-session' | 'wmp-auto-playlist' | 'wmp-copy-protected-music' | 'wmp-device-error' | 'wmp-general-error' | 'wmp-import-audio-cd' | 'wmp-import-playlist' | 'wmp-import-video' | 'wmp-library-error' | 'wmp-library' | 'wmp-missing-disc' | 'wmp-missing-file' | 'wmp-network-error' | 'wmp-performance' | 'wmp-playlist' | 'wmp-plugin' | 'wmp-stream-error' | 'wmp-timed-lyrics' | 'wms-allow-connections' | 'wms-broadcast-alt' | 'wms-broadcast' | 'wms-cache' | 'wms-deny-connections' | 'wms-playlist' | 'wms-streaming-server' | 'wms-troubleshoot' | 'wms-wrapper-file' | 'wmv2' | 'wmv' | 'wri' | 'web-services-printer' | 'webcam' | 'windows-catalog' | 'windows-journal-viewer' | 'windows-journal' | 'windows-media-connect' | 'windows-media-encoder' | 'windows-media-player10' | 'windows-media-player9' | 'windows-media-player-skin' | 'windows-media-services' | 'windows-messenger' | 'windows-movie-maker' | 'windows-picture-and-fax-viewer' | 'windows-update' | 'wireless-connection-settings' | 'wireless-network-connection' | 'wireless-network-setup' | 'wizard' | 'wordpad' | 'workgroup' | 'write-files-to-disc' | 'xml' | 'xps-viewer' | 'xps-document' | 'xpsp3-res-unknown1' | 'xpsp3-res-unknown2' | 'xsl' | 'zip-drive' | 'zip-folder' | 'cd-r' | 'cd-rom' | 'cd-rw' | 'certificate' | 'desktop' | 'dialer' | 'dvd-r' | 'dvd-ram' | 'dvd-rom' | 'dvd-rw' | 'dvd' | 'email' | 'explorer-properties' | 'explorer' | 'fax' | 'firewall' | 'forward' | 'freecell' | 'key' | 'keyboard' | 'minesweeper' | 'mouse' | 'msn' | 'narrator' | 'notepad' | 'paint' | 'pinball' | 'printer' | 'scanner' | 'search' | 'solitaire' | 'volume'

export const isTypeIconPackXp = (value: string) => ['accessibility-wizard', 'accessibility', 'activation', 'add-network-place', 'add-new-hardware', 'add-new-programs', 'add-or-remove-windows-components', 'add', 'additional-settings', 'address-book', 'administrative-tools', 'alert', 'appearance', 'application-window', 'attributes', 'audio-cd', 'audio-devices', 'authorization-manager', 'auto-complete', 'bat', 'blg', 'back', 'backup-wizard', 'backups', 'battery-backup', 'bitmap', 'bluetooth-access-point', 'bluetooth-devices', 'bridged-connection', 'briefcase', 'burn-audio-cd', 'cab', 'css', 'calculator', 'camcorder', 'change-connection-settings', 'change-language', 'change-or-remove-programs', 'charmap', 'checklist', 'chip', 'click-to-record', 'color-profile', 'color-scan', 'command-prompt', 'compact-flash-card', 'component-services', 'compose-a-fax', 'computer-management', 'computer-to-computer-connection', 'configure-your-server-wizard', 'connection-manager', 'connection-status', 'content-advisor', 'control-panel', 'copy-to', 'copy-to-disc', 'copy', 'copying-conflict', 'cover-page-editor', 'critical', 'cut', 'dll', 'dvd-alt', 'data-execution-prevention', 'date-and-region', 'date-and-time', 'default-programs-sp1-version', 'default-programs', 'default', 'delete-confirmation', 'delete-internet-history', 'delete', 'detail-view', 'dial-up-connection', 'digital-camera', 'direct-connection', 'direct-x', 'disable-network-connection', 'discard-fax', 'disconnect-network-drive', 'disk-cleanup', 'disk-defragmenter', 'disk-management', 'display-adaptor', 'display-properties', 'document-search', 'double-click', 'entire-network', 'erase-disc', 'erase', 'event-viewer', 'exit', 'explorer-delete', 'favorites', 'fax-archive', 'fax-console', 'fax-cover-page', 'fax-devices', 'fax-event', 'fax-received-succesfully', 'fax-sender-information', 'fax-sent-succesfully', 'file-and-settings-transfer-wizard', 'floppy-disk', 'folder-closed', 'folder-opened', 'folder-options', 'folder-view-classic', 'folder-view-common-tasks', 'folder-view', 'folders-open-in-new-window', 'folders-open-in-same-window', 'font-similarity-view', 'font', 'font2', 'fonts', 'full-screen', 'gif', 'game-controller', 'generic-audio', 'generic-document', 'generic-media', 'generic-text-document', 'generic-video', 'get-going-with-tablet-pc', 'get-pictures', 'get-support', 'go', 'graph-view', 'grayscale-scan', 'hlp', 'html', 'hearts', 'help-and-support-change-view1', 'help-and-support-change-view2', 'help-and-support-index', 'help-and-support-task-list', 'help-and-support', 'hibernate', 'high-contrast-settings', 'hyper-terminal', 'ie-discuss', 'ie-edit', 'ie-encoding', 'ie-enlarge-image', 'ie-history', 'ie-home', 'ie-media', 'ie-refresh', 'ie-shrink-image', 'ie-size', 'ie-stop', 'inf', 'ir-file-transfer', 'icon-view', 'iexpress', 'important', 'incoming-connections', 'indexing-service', 'information-bar', 'information', 'ink-ball', 'input-panel', 'internet-backgammon', 'internet-checkers', 'internet-connection-wizard', 'internet-explorer6', 'internet-hearts', 'internet-information-services6', 'internet-options', 'internet-reversi', 'internet-shortcut', 'internet-spades', 'jaz-drive', 'jpg', 'java-script', 'journal-note', 'journal-template', 'legacy-floppy-disk', 'local-disk', 'local-security-policy', 'lock', 'login-question', 'logout', 'mp3-player', 'msn-email', 'msn-messenger', 'mswmm', 'magnifier', 'malicious-software-removal-tool', 'manage-server-licenses', 'manage-server-roles', 'manage-your-server', 'map-network-drive', 'maximize', 'media-center-extender-manager', 'media-center-file', 'media-center', 'memory-stick-with-magic-gate', 'memory-stick', 'microsoft-active-sync', 'microsoft-update', 'microsoft-windows-network', 'minimize', 'missing-setup-information', 'mobile-device', 'modem', 'move-to', 'move-this-folder', 'move-to-folder', 'mute', 'my-computer', 'my-documents', 'my-music', 'my-network-places', 'my-pictures', 'my-videos', 'netmeeting', 'network-connection', 'network-connections', 'network-drive-disconnected', 'network-drive', 'network-fax', 'network-folder', 'network-setup', 'network-and-internet', 'network-printer', 'new-folder', 'new-imaging-device', 'new-internet-connection', 'new-network-connection', 'new-printer', 'new-scheduled-task', 'odbc-data-sources', 'oe-attatch', 'oe-create-mail', 'oe-decode', 'oe-encrypt', 'oe-folder-list', 'oe-forward', 'oe-inbox', 'oe-mark-as-read', 'oe-mark-as-unread', 'oe-news-post', 'oe-outbox', 'oe-preview-pane', 'oe-recipients', 'oe-reply-all', 'oe-reply', 'oe-send-and-receive', 'oe-send', 'oe-sent-items', 'oe-sign', 'oe-signature', 'oe-unscramble', 'offline-web-pages', 'on-screen-keyboard', 'open', 'open-type', 'optical-drive', 'outlook-express', 'pcmcia-card', 'packager', 'padlock-alt', 'padlock', 'paste', 'performance-monitor', 'performance', 'phone-and-modem-options', 'phone', 'play', 'pop-up-allowed', 'pop-up-blocked', 'pop-up-information', 'portable-media-devices', 'power-options', 'power-status', 'power', 'print-server-properties', 'print-photos', 'print-to-file', 'printer-missing', 'printers-and-faxes', 'printers-and-hardware', 'privacy', 'programs', 'prohibited', 'properties', 'proxy-server', 'publish-photos-to-web', 'publish-to-web', 'question', 'rtc-share', 'rtf', 'recent-documents', 'record', 'recycle-bin-empty', 'recycle-bin-full', 'redo', 'regional-settings', 'registry-document', 'registry-editor', 'related-web-content', 'remote-access-service', 'remote-assistance', 'remote-desktop-server', 'remote-desktop', 'removable-media', 'rename', 'restart', 'restore-all-items', 'restore', 'restricted', 'router', 'run', 'sd-card-alt', 'sd-card', 'safely-remove-hardware', 'save', 'scanner-and-camera-wizard', 'scanners-and-cameras', 'scheduled-tasks', 'scrap', 'script-component', 'search-results', 'search-for-people', 'security-ok', 'security-alert', 'security-center', 'security-error', 'security-question', 'security-settings', 'send-a-fax', 'serial-connection', 'server-license', 'services', 'settings-alert', 'setup-language', 'setup-skip', 'setup-back', 'setup-task', 'setup', 'shared-folder-alt', 'shared-folder', 'shared-printer', 'sharing-hand', 'shortcut-overlay', 'single-click', 'slideshow', 'smart-card-reader', 'smart-media-card', 'smart-screen', 'sort-alphabetically', 'sort-by-date', 'sort-by-size', 'speech', 'spider-solitaire', 'standby', 'start-menu-programs-alt', 'start-menu-programs', 'sticky-notes', 'stop', 'success', 'support-topic', 'switch-user', 'sync-all', 'sync', 'synchronize', 'system-information', 'system-properties', 'system-restore', 'tiff', 'txt', 'tablet-and-pen-settings', 'take-picture', 'tape-drive2', 'tape-drive', 'task-manager', 'taskbar-and-start-menu', 'theme', 'thumbnail-view', 'tile-view', 'tip-of-the-day', 'tour-xp', 'troubleshoot', 'true-type', 'true-type2', 'tweak-ui', 'uddi-services', 'url', 'undo', 'undock-pc', 'unknown-disc', 'up', 'user-accounts', 'vbs', 'vpn-connection', 'virus-protection', 'volume-alt', 'volume-level', 'wme-broadcast-company-meeting', 'wme-broadcast-live-event', 'wme-capture-audio-or-video', 'wme-capture-screen', 'wme-capture-live-content-for-streaming', 'wme-capture-live-content-locally', 'wme-convert-film', 'wme-convert-a-file', 'wme-custom-session', 'wmp-auto-playlist', 'wmp-copy-protected-music', 'wmp-device-error', 'wmp-general-error', 'wmp-import-audio-cd', 'wmp-import-playlist', 'wmp-import-video', 'wmp-library-error', 'wmp-library', 'wmp-missing-disc', 'wmp-missing-file', 'wmp-network-error', 'wmp-performance', 'wmp-playlist', 'wmp-plugin', 'wmp-stream-error', 'wmp-timed-lyrics', 'wms-allow-connections', 'wms-broadcast-alt', 'wms-broadcast', 'wms-cache', 'wms-deny-connections', 'wms-playlist', 'wms-streaming-server', 'wms-troubleshoot', 'wms-wrapper-file', 'wmv2', 'wmv', 'wri', 'web-services-printer', 'webcam', 'windows-catalog', 'windows-journal-viewer', 'windows-journal', 'windows-media-connect', 'windows-media-encoder', 'windows-media-player10', 'windows-media-player9', 'windows-media-player-skin', 'windows-media-services', 'windows-messenger', 'windows-movie-maker', 'windows-picture-and-fax-viewer', 'windows-update', 'wireless-connection-settings', 'wireless-network-connection', 'wireless-network-setup', 'wizard', 'wordpad', 'workgroup', 'write-files-to-disc', 'xml', 'xps-viewer', 'xps-document', 'xpsp3-res-unknown1', 'xpsp3-res-unknown2', 'xsl', 'zip-drive', 'zip-folder', 'cd-r', 'cd-rom', 'cd-rw', 'certificate', 'desktop', 'dialer', 'dvd-r', 'dvd-ram', 'dvd-rom', 'dvd-rw', 'dvd', 'email', 'explorer-properties', 'explorer', 'fax', 'firewall', 'forward', 'freecell', 'key', 'keyboard', 'minesweeper', 'mouse', 'msn', 'narrator', 'notepad', 'paint', 'pinball', 'printer', 'scanner', 'search', 'solitaire', 'volume'].indexOf(value) >= 0

export type IconPackXpSP2 = 'antenna-signal' | 'antenna' | 'internet-connection-firewall-locked-down' | 'internet-connection-firewall-off' | 'internet-connection-firewall' | 'search-for-wireless-network' | 'security-options' | 'wireless-network-connection'

export const isTypeIconPackXpSP2 = (value: string) => ['antenna-signal', 'antenna', 'internet-connection-firewall-locked-down', 'internet-connection-firewall-off', 'internet-connection-firewall', 'search-for-wireless-network', 'security-options', 'wireless-network-connection'].indexOf(value) >= 0

export type IconPackLonghorn = 'active-contact' | 'business-contact' | 'contact-offline' | 'directory-services' | 'my-games' | 'new-contact' | 'parental-controls' | 'pending-contact' | 'presentation-host2' | 'presentation-host3' | 'presentation-host4' | 'presentation-host5' | 'presentation-host' | 'presentation-platform' | 'usb'

export const isTypeIconPackLonghorn = (value: string) => ['active-contact', 'business-contact', 'contact-offline', 'directory-services', 'my-games', 'new-contact', 'parental-controls', 'pending-contact', 'presentation-host2', 'presentation-host3', 'presentation-host4', 'presentation-host5', 'presentation-host', 'presentation-platform', 'usb'].indexOf(value) >= 0

export type IconPackWhistler = 'accessibility' | 'appearance-and-themes' | 'back' | 'explorer-delete' | 'favorites' | 'forward' | 'help-and-support' | 'ie-favorites' | 'ie-history' | 'ie-home' | 'ie-personal-bar' | 'ie-refresh' | 'ie-search' | 'ie-stop' | 'internet-options' | 'orb-drive' | 'performance' | 'programs' | 'recycle-bin-empty' | 'recycle-bin-full' | 'redo' | 'rename' | 'run' | 'sd-card' | 'switch-user' | 'system-properties' | 'undo' | 'up' | 'update' | 'user-accounts' | 'volume' | 'windows-media-player7'

export const isTypeIconPackWhistler = (value: string) => ['accessibility', 'appearance-and-themes', 'back', 'explorer-delete', 'favorites', 'forward', 'help-and-support', 'ie-favorites', 'ie-history', 'ie-home', 'ie-personal-bar', 'ie-refresh', 'ie-search', 'ie-stop', 'internet-options', 'orb-drive', 'performance', 'programs', 'recycle-bin-empty', 'recycle-bin-full', 'redo', 'rename', 'run', 'sd-card', 'switch-user', 'system-properties', 'undo', 'up', 'update', 'user-accounts', 'volume', 'windows-media-player7'].indexOf(value) >= 0

export type IconPackApplications = 'acrobat-installer' | 'klite-codec' | 'pdf-file' | 'vlc' | 'winrar3' | 'winrar6'

export const isTypeIconPackApplications = (value: string) => ['acrobat-installer', 'klite-codec', 'pdf-file', 'vlc', 'winrar3', 'winrar6'].indexOf(value) >= 0

export const iconPacks = {

  "xp": {files: Xp, validator: isTypeIconPackXp},
  "xpsp2": {files: XpSP2, validator: isTypeIconPackXpSP2},
  "longhorn": {files: Longhorn, validator: isTypeIconPackLonghorn},
  "whistler": {files: Whistler, validator: isTypeIconPackWhistler},
  "applications": {files: Applications, validator: isTypeIconPackApplications},
}

