export type XPIcon = "7z-file" |
  "access" |
  "account-wizard" |
  "app-wizard" |
  "audio-file" |
  "backup" |
  "bluetooth" |
  "cabfile" |
  "calc" |
  "camera" |
  "card-reader" |
  "cd-audio" |
  "cd-drive" |
  "cd-music" |
  "cd-r" |
  "cd-rom" |
  "cd-rw" |
  "certificate" |
  "char-map" |
  "check" |
  "clean-manager" |
  "config-file" |
  "config-text-file" |
  "danger-orange" |
  "danger" |
  "defender-critical" |
  "defender-warning" |
  "defender" |
  "defrag" |
  "desktop-customization" |
  "desktop" |
  "dialer" |
  "directx-dialog" |
  "disk-generic" |
  "drive" |
  "dvd-drive" |
  "dvd-r" |
  "dvd-ram" |
  "dvd-rom" |
  "dvd-rw" |
  "dvd" |
  "eject" |
  "email" |
  "envelope" |
  "ethernet-globe" |
  "execute" |
  "explorer" |
  "fax" |
  "file-moviemaker" |
  "file-photo" |
  "file-search" |
  "file" |
  "firewall" |
  "floppy-drive" |
  "floppy" |
  "folder-audio" |
  "folder-document" |
  "folder-group" |
  "folder-pictures" |
  "folder-scanned-documents" |
  "folder-search" |
  "folder-shared" |
  "folder-video" |
  "folder" |
  "font-a-lower" |
  "font-a" |
  "font-directory" |
  "font-o" |
  "font-tt-g" |
  "font-tt" |
  "freecell" |
  "gamepad" |
  "globe" |
  "gloss-check-x" |
  "gloss-check-y" |
  "hard-disk-drive" |
  "hardware-wizard" |
  "iexplorer" |
  "image-file" |
  "info-baloon" |
  "info-circle" |
  "input-tablet" |
  "internet-settings" |
  "internet_document" |
  "iomega-zip-reader" |
  "key-manager" |
  "key" |
  "keyboard" |
  "minesweeper" |
  "mmc" |
  "mobile-modem" |
  "moviemaker" |
  "msn" |
  "multimedia-file" |
  "narrator" |
  "network-disk" |
  "network-hard-disk-disconnected" |
  "network-hard-disk" |
  "network-home" |
  "no-check" |
  "notepad" |
  "paint-file" |
  "paint" |
  "pc-info" |
  "pda" |
  "pinball" |
  "power-config" |
  "power-lock" |
  "power-turnoff" |
  "printer" |
  "recyclebin-full" |
  "recyclebin" |
  "scanner" |
  "script-file" |
  "sd-card" |
  "search" |
  "settings" |
  "sfx-file" |
  "solitaire" |
  "speaker-fixed" |
  "spider" |
  "star" |
  "start" |
  "task-manager" |
  "terminal" |
  "text-file" |
  "times" |
  "unknown-file-question" |
  "unknown-file" |
  "users" |
  "video-file" |
  "volume-mixer" |
  "volume" |
  "walkman" |
  "wifi-0" |
  "wifi-1" |
  "wifi-3" |
  "wifi-4" |
  "wifi-5" |
  "wifi-6" |
  "wifi-settings" |
  "wifi" |
  "windows-update" |
  "winrar"
