# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Inkscape Image Conversion

on:
  workflow_dispatch:


jobs:
  generate_svg:

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:inkscape.dev/stable
          sudo apt update
          sudo apt install -y inkscape python3-lxml python3-pytest python3-pil python3-pytest-cov


      - run: npm ci

      # https://gitlab:com/inkscape/inkscape/-/issues/4716:
      - run: SELF_CALL=BLAHAJ npm run convert-svg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: SVG Generation with InkScape

