# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run generate-icons
    - run: npm run build --if-present
      env:
        NODE_OPTIONS: "--max_old_space_size=8192"
    - name: NPM Publish XP Icon Set
  # You may pin to the exact commit or the version.
  # uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
      uses: JS-DevTools/npm-publish@v3.1.1
      with:
        # The NPM access token to use when publishing
        token: ${{ secrets.NPM_TOKEN }}
        # The path to your package or its package.json file
        package: ./dist/ngx-xp-icons

