on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag to utilize'
        required: true


name: Create Release

jobs:
  build:

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build artifact
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - run: sed -i '/^dist$/d' .gitignore
      - run: git config set user.name "GitHub Actions" && git config set user.email "github-action-${{ github.run_id }}@noreply.com"
      - run: git checkout -b release-${{ github.event.inputs.version }}
      - run: git add . && git commit -m "Release ${{ github.event.inputs.version }}"
      - run: git push --set-upstream origin release-${{ github.event.inputs.version }}
      - run: git tag v${{ github.event.inputs.version }} && git push origin v${{ github.event.inputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated creation
          draft: false
          prerelease: false
