on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag to utilize'
        required: true


name: Create Release

jobs:
  build:

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - run: sed -i '/^\/dist$/d' .gitignore

      - name: Building artefact
        run: npm run build --if-present
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: GitHub Actions

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: github-action-${{ github.run_id }}@noreply.com
          message: Release ${{ github.event.inputs.version }}
          new_branch: release-${{ github.event.inputs.version }}
          push: true
          tag: v${{ github.event.inputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated creation
          draft: false
          prerelease: false
